# Binomial Distributions
In this project, we will use NumPy to create simulations and compute proportions for the following outcomes.

1. A fair coin flip produces heads
2. Five fair coin flips produce exactly one head
3. Ten fair coin flips produce exactly four heads
4. Five biased coin flips with P(H) = 0.8 produce exactly five heads
5. Ten biased coin flips with P(H) = 0.15 produce at least three heads

In [1]:
# import numpy
import numpy as np

### 1. A fair coin flip produces heads

In [2]:
# simulate 1 million tests of one fair coin flip
# The output of these tests are the # successes, or # heads
# The following produces 1 flip with probability of success = 0.5
# And repeat that test 1 million times.
tests = np.random.binomial(1, 0.5, int(1e6))

# The output is the number of heads in each test of the million
print(tests)

[0 0 0 ... 0 0 1]


In [3]:
# tests that produced 1 heads
# (tests == 1) returns array([False, False, False, ...,  True, False, False])
tests == 1

array([False, False, False, ..., False, False,  True])

In [4]:
# so calculating the mean of that array, calculate the proportion of the True to False elements
(tests == 1).mean()

0.500021

### 2. Five fair coin flips produce exactly one head

In [5]:
# simulate 1 million tests of five fair coin flips
tests = np.random.binomial(n = 5, p = 0.5, size = int(1e6))
print(tests)

[2 4 0 ... 4 1 2]


In [6]:
# proportion of tests that produced 1 head
(tests == 1).mean()

0.156208

### 3. Ten fair coin flips produce exactly four heads

In [7]:
# simulate 1 million tests of ten fair coin flips
tests = np.random.binomial(n = 10, p = 0.5, size = int(1e6))
print(tests)

[5 5 4 ... 7 2 4]


In [8]:
# tests that produced 4 heads
tests == 4

array([False, False,  True, ..., False, False,  True])

In [9]:
# proportion of tests that produced 4 heads
(tests == 4).mean()

0.20458

### 4. Five biased coin flips with P(H) = 0.8 produce exactly five heads

In [10]:
# simulate 1 million tests of five biased coin flips
tests = np.random.binomial(n = 5, p = 0.8, size = int(1e6))
print(tests)

[5 5 5 ... 3 4 5]


In [11]:
# proportion of tests that produced 5 heads
(tests == 5).mean()

0.327502

### 5. Ten biased coin flips with P(H) = 0.15 produce at least 3 heads

In [12]:
# simulate 1 million tests of ten biased coin flips
tests = np.random.binomial(n= 10, p = 0.15, size = int(1e6))
print(tests)

[1 1 2 ... 0 3 1]


In [13]:
# tests that produced at least 3 heads
tests >= 3

array([False, False, False, ..., False,  True, False])

In [15]:
# proportion of tests that produced at least 3 heads
(tests >= 3).mean()

0.180203