# Simulating Coin Flips

NumPy has a module for random sampling, that makes it really easy for us to simulate random events like coin flips and Python. 

We're going to start with a simple example, simulating a single coin flip. 

For this, we'll use a function called randint. This generates however many random integers, we specify between a lower bound inclusive and upper bound exclusive. We can use these integers to represent the outcomes of our events, like coin flips.

Note that, we will represent Head with 0, and Tail with 1:

Head --> 0

Tail --> 1

In [1]:
import numpy as np

In [2]:
# We call randint from NumPy's random sampling module like this.
# Let's use zero to represent heads and one to represent tails.
# Let's make this function randomly produce zero or one.
# The lower bound would be zero and the highest would be two, because it's exclusive.
# Since the lower bound is zero,
# this is actually the default.
# We don't need to include it.
# If we run the cell again and again,
# we'll keep getting a random outcome of zero or one 
np.random.randint(2)

0

In [3]:
# or we can specify a size to just give us more events.
# Now, we have the results of 10,000 random coin flips.
np.random.randint(2, size = 10000)

array([0, 1, 1, ..., 1, 0, 1])

In [4]:
# The average of these outcomes produced here should be very close to 0.5,
# since right now there's an equal probability of getting a zero or a one.
np.random.randint(2, size=10000).mean()

0.5101

In [5]:
# But if we want to flip a biased coin,
# that had a higher probability of landing on heads,
# There's actually another function for this called random.choice.
# This function works a little differently.
# It randomly chooses a number of values from an array that you provide and you
# can also give it a set of probabilities for each value in that array.
# Let's call random.choice and give it the array of the possible outcomes zero and one.
# If we don't specify probabilities,
# it gives us each value and an equal probability by default.
np.random.choice([0, 1], size = 10000)

array([1, 0, 0, ..., 1, 0, 1])

In [6]:
# We can run this similar to the above example in this way.
# So the average is very close to 0.5 Again.
np.random.choice([0, 1], size = 10000).mean()

0.4981

In [7]:
# To make this a biased coin,
# we can specify the parameter p with an array of probabilities.
# Say 0.8 for heads and 0-2 for tails.
np.random.choice([0, 1], size = 10000, p = [0.8, 0.2])

array([0, 0, 1, ..., 1, 0, 0])

In [8]:
# Now, you can see that the mean is close to 0.2 which makes
# sense, because the zero or heads should be chosen 80% of the time.
np.random.choice([0, 1], size = 10000, p = [0.8, 0.2]).mean()

0.2008

You probably noticed that the mean values we get from
these outcomes don't always reflect the true probabilities perfectly.

However, they do tend to reflect the true probability
more closely as we increase the number of flips.
